owner: dataforcanada
repo: status.dataforcanada.org

sites:
  - name: Main Website
    url: https://www.dataforcanada.org
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/www.dataforcanada.org/refs/heads/main/static/logo.svg
  - name: Production Ready Data
    url: https://data-01.dataforcanada.org
  - name: Data in the Lab
    url: https://data-01.labs.dataforcanada.org
  - name: Data in the Lab
    url: https://data-01.labs.dataforcanada.org
assignees:
  - diegoripley

status-website:
  cname: status.dataforcanada.org
  theme: light
  logoUrl: https://raw.githubusercontent.com/dataforcanada/www.dataforcanada.org/refs/heads/main/static/logo.svg
  name: Status Page for the Data for Canada Project
  introTitle: "Status Page for the Data for Canada Project"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/dataforcanada/status.dataforcanada.org).
  navbar:
    - title: Status
      href: /
    - title: Status Updates
      href: https://github.com/dataforcanada/status.dataforcanada.org
    - title: Prod
      href: https://www.dataforcanada.org
    - title: Labs
      href: https://www.dataforcanada.org

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

user-agent: diegoripley