owner: dataforcanada
repo: status.dataforcanada.org

sites:
  - name: P2P Tracker (Labs)
    url: https://tracker.labs.dataforcanada.org/announce
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/static.dataforcanada.org/refs/heads/main/assets/svg/peer-to-peer-icon.svg
  - name: Main Website
    url: https://www.dataforcanada.org
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/static.dataforcanada.org/refs/heads/main/assets/svg/cloudflare-logo.svg
  - name: Production Ready Data
    url: https://data-01.dataforcanada.org
  - name: Data in the Lab
    url: https://data-01.labs.dataforcanada.org
    type: globalping
    check: "http"
    location: "Toronto+CA"
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/static.dataforcanada.org/refs/heads/main/assets/svg/cloudflare-logo.svg
  - name: Static Assets (Prod)
    url: https://static-01.dataforcanada.org
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/static.dataforcanada.org/refs/heads/main/assets/svg/cloudflare-logo.svg
  - name: Static Assets (Labs)
    url: https://static-01.labs.dataforcanada.org
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/static.dataforcanada.org/refs/heads/main/assets/svg/cloudflare-logo.svg
  - name: Tile Server (Prod)
    url: https://tiles-01.dataforcanada.org
    expectedStatusCodes:
      - 404
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/static.dataforcanada.org/refs/heads/main/assets/svg/cloudflare-logo.svg
  - name: Tile Server (Labs)
    url: https://tiles-01.labs.dataforcanada.org
    expectedStatusCodes:
      - 404
    faviconSvg: https://raw.githubusercontent.com/dataforcanada/static.dataforcanada.org/refs/heads/main/assets/svg/cloudflare-logo.svg
  #- name: Torrent Index (Labs)
  #  url: https://index.labs.dataforcanada.org
  #- name: Panoramax (Prod)
  #  url: https://panoramax-01.dataforcanada.org
  #- name: Panoramax (Labs)
  #  url: https://panoramax-01.labs.dataforcanada.org
  #- name: Martin (Prod)
  #  url: https://martin-01.dataforcanada.org
  #- name: Martin (Labs)
  #  url: https://martin-01.labs.dataforcanada.org
  #- name: Pelias (Prod)
  #  url: https://pelias-01.dataforcanada.org
  #- name: Pelias (Labs)
  #  url: https://pelias-01.labs.dataforcanada.org
  #- name: GeoServer (Prod)
  #  url: https://geoserver-01.dataforcanada.org
  #- name: GeoServer (Labs)
  #  url: https://geoserver-01.labs.dataforcanada.org
  #- name: ZOO-Project (Prod)
  #  url: https://zoo-project-01.dataforcanada.org
  #- name: ZOO-Project (Labs)
  #  url: https://zoo-project-01.labs.dataforcanada.org
  #- name: BBOX Server (Prod)
  #  url: https://bbox-01.dataforcanada.org
  #- name: BBOX Server (Labs)
  #  url: https://bbox-01.labs.dataforcanada.org
  #- name: Torrent Index (Prod)
  #  url: https://index.dataforcanada.org
  #- name: Source Code
  #  url: https://git.dataforcanada.org
assignees:
  - diegoripley

status-website:
  cname: status.dataforcanada.org
  theme: light
  logoUrl: https://raw.githubusercontent.com/dataforcanada/www.dataforcanada.org/refs/heads/main/static/logo.svg
  name: Status Page for the Data for Canada Project
  introTitle: "Status Page for the Data for Canada Project"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/dataforcanada/status.dataforcanada.org).
  navbar:
    - title: Status Updates
      href: https://github.com/dataforcanada/status.dataforcanada.org
    - title: Main Website
      href: https://www.dataforcanada.org

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

user-agent: diegoripley
